Remove submodule handling now that no release channel uses them
portage-stable and coreos-overlay used to be submodules of scripts, but
this is no longer true in any release channel, so we can drop any code
that handles the migration.

Submodule-related arguments are still passed to git where they make
sense just in case we do start using submodules that don't need special
handling.

Some of these scripts seem a little overly complex now that they only
handle the scripts repo, but let's not rewrite them now.

Signed-off-by: James Le Cuirot <jlecuirot@microsoft.com>

diff --git a/show-changes b/show-changes
--- a/show-changes
+++ b/show-changes
@@ -7,14 +7,12 @@ SCRIPTFOLDER="$(dirname "$(readlink -f "$0")")"
 if [ $# -lt 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
   echo "Usage: $0 OLD [NEW]"
   echo "Shows the changes between the git references by assembling the changelog/ folder entries"
-  echo "By default the script assumes that it is being run in the folder that contains the coreos-overlay, portage-stable, and scripts repository folders. Set SCRIPTS_REPO, COREOS_OVERLAY_REPO and PORTAGE_REPO to contain the paths to the respective repos if the default assumption is wrong."
+  echo "By default the script assumes that it is being run in the folder that contains the scripts repository folder. Set SCRIPTS_REPO to contain the path to the repo if the default assumption is wrong."
   echo "The NEW reference can be omitted and will then default to HEAD."
   exit 1
 fi
 
 : "${SCRIPTS_REPO:=scripts}"
-: "${COREOS_OVERLAY_REPO:=coreos-overlay}"
-: "${PORTAGE_STABLE_REPO:=portage-stable}"
 
 OLD="$1"
 NEW="${2-HEAD}"
@@ -32,7 +30,7 @@ fi
 echo "_Changes since **${OLD_FMT}**_"
 
 if [[ ${FETCH} = 1 ]]; then
-  for repo in coreos-overlay portage-stable scripts; do
+  for repo in scripts; do
     var_name=${repo//-/_}
     var_name="${var_name^^}_REPO"
     if [[ -d ${!var_name} ]]; then
@@ -61,44 +59,15 @@ for section in security bugfixes changes updates; do
       exit 1
   esac
   echo
-  for repo in coreos-overlay portage-stable scripts; do
+  for repo in scripts; do
     var_name=${repo//-/_}
     var_name="${var_name^^}_REPO"
     OLDREF="${OLD}"
     NEWREF="${NEW}"
-    OLDREPOPATH="${!var_name}"
-    NEWREPOPATH="${!var_name}"
-    OLDPREPEND=""
-    NEWPREPEND=""
-    if [ "${repo}" != "scripts" ]; then
-      # Check if we are in the monorepo case where we can use the scripts ref or not
-      if [ "$(git -C "${SCRIPTS_REPO}" show "${OLD}":.gitmodules 2>/dev/null)" != "" ]; then
-        # Old version is not a monorepo but has submodules.
-        # Find the pinned submodule refs because there may be no release tags inside the submodules
-        # Pipe to awk instead of using --object-only for git 2.35 support
-        OLDREF=$(git -C "${SCRIPTS_REPO}" ls-tree "${OLD}" "sdk_container/src/third_party/${repo}" | awk '{print $3 }')
-        # We can't assume anymore that the submodule repo is available under scripts/
-        if [ ! -d "${OLDREPOPATH}" ]; then
-          git clone "git@github.com:flatcar/${repo}.git" "${OLDREPOPATH}"
-        fi
-      else
-        OLDPREPEND="sdk_container/src/third_party/${repo}/"
-        OLDREPOPATH="${SCRIPTS_REPO}"
-      fi
-      if [ "$(git -C "${SCRIPTS_REPO}" show "${NEW}":.gitmodules 2>/dev/null)" != "" ]; then
-        # New version is not a monorepo but has submodules.
-        NEWREF=$(git -C "${SCRIPTS_REPO}" ls-tree "${NEW}" "sdk_container/src/third_party/${repo}" | awk '{print $3 }')
-        if [ ! -d "${NEWREPOPATH}" ]; then
-          git clone "git@github.com:flatcar/${repo}.git" "${NEWREPOPATH}"
-        fi
-      else
-        NEWPREPEND="sdk_container/src/third_party/${repo}/"
-        NEWREPOPATH="${SCRIPTS_REPO}"
-      fi
-    fi
-    if [ "${section}" = "security" ] && [ "${repo}" = "coreos-overlay" ]; then
-      FROM_KERNEL=$(git -C "${OLDREPOPATH}" show "${OLDREF}":"${OLDPREPEND}"sys-kernel/coreos-kernel/ | grep -m 1 'coreos-kernel-.*\.ebuild' | cut -d - -f 3 | cut -d . -f 1-3)
-      TO_KERNEL=$(git -C "${NEWREPOPATH}" show "${NEWREF}":"${NEWPREPEND}"sys-kernel/coreos-kernel/ | grep -m 1 'coreos-kernel-.*\.ebuild' | cut -d - -f 3 | cut -d . -f 1-3)
+    REPOPATH="${!var_name}"
+    if [ "${section}" = "security" ] && [ "${repo}" = "scripts" ]; then
+      FROM_KERNEL=$(git -C "${REPOPATH}" show "${OLDREF}":sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/ | grep -m 1 'coreos-kernel-.*\.ebuild' | cut -d - -f 3 | cut -d . -f 1-3)
+      TO_KERNEL=$(git -C "${REPOPATH}" show "${NEWREF}":sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-kernel/ | grep -m 1 'coreos-kernel-.*\.ebuild' | cut -d - -f 3 | cut -d . -f 1-3)
       if [ "${FROM_KERNEL}" != "${TO_KERNEL}" ]; then
         KERNEL_ENTRIES=$("${SCRIPTFOLDER}"/show-fixed-kernel-cves.py -f "${FROM_KERNEL}" -t "${TO_KERNEL}")
         if [ "${KERNEL_ENTRIES}" != "" ]; then
@@ -107,18 +76,7 @@ for section in security bugfixes changes updates; do
       fi
     fi
 
-    # The assumption is that the old ref is really older, so we can assume that old would have submodules while new doesn't have them anymore
-    if [ "${OLDREPOPATH}" != "${NEWREPOPATH}" ] && [ "${NEWREPOPATH}" = "${SCRIPTS_REPO}" ]; then
-      # One patch before the ./checkout helper disappeared we still had submodules
-      LAST_SUBMOD_SCRIPTS_REF="$(git -C "${SCRIPTS_REPO}" rev-list -n 1 "${NEWREF}" -- checkout)~1"
-      LAST_SUBMOD_REF=$(git -C "${SCRIPTS_REPO}" ls-tree "${LAST_SUBMOD_SCRIPTS_REF}" "sdk_container/src/third_party/${repo}" | awk '{print $3 }')
-      # The patch that removed the submodule overrides README has the merge history
-      FIRST_MONO_REF=$(git -C "${SCRIPTS_REPO}" rev-list -n 1 "${NEWREF}" -- sdk_container/git-override/README.md)
-      git -C "${OLDREPOPATH}" difftool --no-prompt --extcmd='sh -c "cat \"$REMOTE\"" --' "${OLDREF}..${LAST_SUBMOD_REF}" -- "${OLDPREPEND}changelog/${section}/" | sort || { echo "Error: git difftool failed" ; exit 1 ; }
-      git -C "${NEWREPOPATH}" difftool --no-prompt --extcmd='sh -c "cat \"$REMOTE\"" --' "${FIRST_MONO_REF}..${NEWREF}" -- "${NEWPREPEND}changelog/${section}/" | sort || { echo "Error: git difftool failed" ; exit 1 ; }
-    else
-      git -C "${NEWREPOPATH}" difftool --no-prompt --extcmd='sh -c "cat \"$REMOTE\"" --' "${OLDREF}..${NEWREF}" -- "${NEWPREPEND}changelog/${section}/" | sort || { echo "Error: git difftool failed" ; exit 1 ; }
-    fi
+    git -C "${REPOPATH}" difftool --no-prompt --extcmd='sh -c "cat \"$REMOTE\"" --' "${OLDREF}..${NEWREF}" -- "changelog/${section}/" | sort || { echo "Error: git difftool failed" ; exit 1 ; }
     # The -x 'sh -c "cat \"$REMOTE\"" --' command assumes that new changes have their own changelog files,
     # and thus ignores the LOCAL file (which is the empty /dev/null) and prints out the REMOTE completly.
     # If an existing file got changed, we assume that this is just a correction for the old change but
