update-repos: cleanup from previous patch
Signed-off-by: Thilo Fromm <thilo@kinvolk.io>

diff --git a/update-repos b/update-repos
--- a/update-repos
+++ b/update-repos
@@ -62,18 +62,20 @@ function update-branches() {
   git push --tags "${ORIGIN}"
 }
 
+
 if [ $# -eq 1 -a -d "${PWD}/$1" ] ; then
     PREFIX="$1"
     echo "Using existing directory $PREFIX"
+    # we're not cleaning up this one since it's user provided
 else
     PREFIX=$(mktemp -d "${PWD}/.update-repos.XXXXXXXXXX")
     echo "Created new directory $PREFIX"
+    # clean up
+    trap '{ export EXT="$?"; rm -rf "${PREFIX}" && exit "${EXT}"; }' EXIT
 fi
 
 cd "${PREFIX}"
 
-# clean up
-#trap '{ export EXT="$?"; rm -rf "${PREFIX}" && exit "${EXT}"; }' EXIT
 
 for repo in "${REPOS[@]}"; do
   [ ! -d "${repo}" ] && git clone "git@github.com:flatcar-linux/${repo}"
